// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./../components/NavBar";
export const metadata = {
  title: "المجمع الطبي بكوبري القبة",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
