// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./../components/NavBar";
import { UserProvider } from "@/contexts/UserContext";
export const metadata = {
  title: "المجمع الطبي بكوبري القبة",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
