import formatOracleDate from "@/lib/utils";

const {
  connectToDatabase,
  closeDatabaseConnection,
  runQuery,
} = require("../../lib/db");

export default async function handler(req, res) {
  let connection;

  try {
    connection = await connectToDatabase();

    // Your database queries or operations go here
    const FD = formatOracleDate(req.query.fdate);
    const TD = formatOracleDate(req.query.tdate);
    const query = `
    SELECT 1 ORD_FLG,RANK_CLASS.RANK_CLASS,RANK_CLASS.RANK_CLASS_NAME,CLINIC.CLINIC_OUT_NAME,RESERVE_CLINIC.PATIENT_NUM
FROM   RESERVE_CLINIC,V_CLINIC_NAME CLINIC,SPECIALISIM,PATIENT P1,RANK_CLASS
WHERE RESERVE_CLINIC.PATIENT_NUM = P1.PATIENT_NUM
AND     P1.RANK = RANK_CLASS.RANK_CODE
AND     P1.KINSHIP_PATIENT_NUM IS NULL
AND     RESERVE_CLINIC.CLINIC_CODE = CLINIC.CLINIC_CODE
AND     RESERVE_CLINIC.HOSP_CODE    = CLINIC.HOSP_CODE
AND     CLINIC.SPECIALISIM_CODE = SPECIALISIM.SPECIALISIM_CODE
AND     RANK_CLASS.RANK_CLASS < 99
AND     CLINIC.SPECIALISIM_CODE IN (97,86)
AND     CLINIC.CLINIC_CODE NOT IN (3659,30111150001,30111120001,20022190001,31201110017)
AND     RESERVE_CLINIC.RESERVE_DATE >= '${FD}'
AND     RESERVE_CLINIC.RESERVE_DATE <= '${TD}'
UNION ALL
SELECT 1 ORD_FLG,25 RANK_CLASS,'ÚÇÆáÇÊ ÖÈÇØ' RANK_CLASS_NAME,CLINIC.CLINIC_OUT_NAME,RESERVE_CLINIC.PATIENT_NUM
FROM   RESERVE_CLINIC,V_CLINIC_NAME CLINIC,SPECIALISIM,PATIENT P1,RANK_CLASS,PATIENT P2
WHERE RESERVE_CLINIC.PATIENT_NUM = P1.PATIENT_NUM
AND     P1.RANK = RANK_CLASS.RANK_CODE
AND     P1.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM
AND     P2.RANK IN (1,2,3,4,5,6,7,8,9,10,11)
AND     RESERVE_CLINIC.CLINIC_CODE = CLINIC.CLINIC_CODE
AND     RESERVE_CLINIC.HOSP_CODE    = CLINIC.HOSP_CODE
AND     CLINIC.SPECIALISIM_CODE = SPECIALISIM.SPECIALISIM_CODE
AND     RANK_CLASS.RANK_CLASS < 99
AND     CLINIC.SPECIALISIM_CODE IN (97,86)
AND     CLINIC.CLINIC_CODE NOT IN (3659,30111150001,30111120001,20022190001,31201110017)
AND     RESERVE_CLINIC.RESERVE_DATE >= '${FD}'
AND     RESERVE_CLINIC.RESERVE_DATE <= '${TD}'
UNION ALL
SELECT 1 ORD_FLG,26 RANK_CLASS,'ÚÇÆáÇÊ ÕÝ' RANK_CLASS_NAME,CLINIC.CLINIC_OUT_NAME,RESERVE_CLINIC.PATIENT_NUM
FROM   RESERVE_CLINIC,V_CLINIC_NAME CLINIC,SPECIALISIM,PATIENT P1,RANK_CLASS,PATIENT P2
WHERE RESERVE_CLINIC.PATIENT_NUM = P1.PATIENT_NUM
AND     P1.RANK = RANK_CLASS.RANK_CODE
AND     P1.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM
AND     P2.RANK IN (12,13,14,15,16,17,18,19,23)
AND     RESERVE_CLINIC.CLINIC_CODE = CLINIC.CLINIC_CODE
AND     RESERVE_CLINIC.HOSP_CODE    = CLINIC.HOSP_CODE
AND     CLINIC.SPECIALISIM_CODE = SPECIALISIM.SPECIALISIM_CODE
AND     RANK_CLASS.RANK_CLASS < 99
AND     CLINIC.SPECIALISIM_CODE IN (97,86)
AND     CLINIC.CLINIC_CODE NOT IN (3659,30111150001,30111120001,20022190001,31201110017)
AND     RESERVE_CLINIC.RESERVE_DATE >= '${FD}'
AND     RESERVE_CLINIC.RESERVE_DATE <= '${TD}'

UNION ALL

SELECT 2 ORD_FLG,RANK_CLASS.RANK_CLASS,RANK_CLASS.RANK_CLASS_NAME,CLINIC.CLINIC_OUT_NAME,RESERVE_CLINIC.PATIENT_NUM
FROM   RESERVE_CLINIC,V_CLINIC_NAME CLINIC,SPECIALISIM,PATIENT P1,RANK_CLASS
WHERE RESERVE_CLINIC.PATIENT_NUM = P1.PATIENT_NUM
AND     P1.RANK = RANK_CLASS.RANK_CODE
AND     P1.KINSHIP_PATIENT_NUM IS NULL
AND     RESERVE_CLINIC.CLINIC_CODE = CLINIC.CLINIC_CODE
AND     RESERVE_CLINIC.HOSP_CODE    = CLINIC.HOSP_CODE
AND     CLINIC.SPECIALISIM_CODE = SPECIALISIM.SPECIALISIM_CODE
AND     RANK_CLASS.RANK_CLASS < 99
AND     CLINIC.CLINIC_CODE IN (3659,30111150001,30111120001,20022190001,31201110017)
AND     RESERVE_CLINIC.RESERVE_DATE >= '${FD}'
AND     RESERVE_CLINIC.RESERVE_DATE <= '${TD}'
UNION ALL
SELECT 2 ORD_FLG,25 RANK_CLASS,'ÚÇÆáÇÊ ÖÈÇØ' RANK_CLASS_NAME,CLINIC.CLINIC_OUT_NAME,RESERVE_CLINIC.PATIENT_NUM
FROM   RESERVE_CLINIC,V_CLINIC_NAME CLINIC,SPECIALISIM,PATIENT P1,RANK_CLASS,PATIENT P2
WHERE RESERVE_CLINIC.PATIENT_NUM = P1.PATIENT_NUM
AND     P1.RANK = RANK_CLASS.RANK_CODE
AND     P1.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM
AND     P2.RANK IN (1,2,3,4,5,6,7,8,9,10,11)
AND     RESERVE_CLINIC.CLINIC_CODE = CLINIC.CLINIC_CODE
AND     RESERVE_CLINIC.HOSP_CODE    = CLINIC.HOSP_CODE
AND     CLINIC.SPECIALISIM_CODE = SPECIALISIM.SPECIALISIM_CODE
AND     RANK_CLASS.RANK_CLASS < 99
AND     CLINIC.CLINIC_CODE IN (3659,30111150001,30111120001,20022190001,31201110017)
AND     RESERVE_CLINIC.RESERVE_DATE >= '${FD}'
AND     RESERVE_CLINIC.RESERVE_DATE <= '${TD}'
UNION ALL
SELECT 2 ORD_FLG,26 RANK_CLASS,'ÚÇÆáÇÊ ÕÝ' RANK_CLASS_NAME,CLINIC.CLINIC_OUT_NAME,RESERVE_CLINIC.PATIENT_NUM
FROM   RESERVE_CLINIC,V_CLINIC_NAME CLINIC,SPECIALISIM,PATIENT P1,RANK_CLASS,PATIENT P2
WHERE RESERVE_CLINIC.PATIENT_NUM = P1.PATIENT_NUM
AND     P1.RANK = RANK_CLASS.RANK_CODE
AND     P1.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM
AND     P2.RANK IN (12,13,14,15,16,17,18,19,23)
AND     RESERVE_CLINIC.CLINIC_CODE = CLINIC.CLINIC_CODE
AND     RESERVE_CLINIC.HOSP_CODE    = CLINIC.HOSP_CODE
AND     CLINIC.SPECIALISIM_CODE = SPECIALISIM.SPECIALISIM_CODE
AND     RANK_CLASS.RANK_CLASS < 99
AND     CLINIC.CLINIC_CODE IN (3659,30111150001,30111120001,20022190001,31201110017)
AND     RESERVE_CLINIC.RESERVE_DATE >= '${FD}'
AND     RESERVE_CLINIC.RESERVE_DATE <= '${TD}'
    `;
    const result = await runQuery(query);
    res.status(200).json({ success: true, data: result });
  } catch (err) {
    console.error("Error in API endpoint:", err);
    res.status(500).json({ success: false, error: "Internal Server Error" });
  } finally {
    if (connection) {
      await closeDatabaseConnection(connection);
    }
  }
}
