import formatOracleDate from "@/lib/utils";

const {
  connectToDatabase,
  closeDatabaseConnection,
  runQuery,
} = require("../../lib/db");

export default async function handler(req, res) {
  let connection;

  try {
    connection = await connectToDatabase();

    // Your database queries or operations go here
    const DATE_IN = req.query.datein;
    const query = `
    SELECT PATIENT.RANK,V_RANKS.RAMK_NAME,ARRIVAL.ARRIVAL_TYPE,V_ARRIVAL_TYPE.TYPE_NAME,ARRIVAL.PATIENT_NUM
FROM ARRIVAL,PATIENT,V_RANKS,V_ARRIVAL_TYPE
WHERE ARRIVAL.PATIENT_NUM = PATIENT.PATIENT_NUM
AND     PATIENT.RANK = V_RANKS.RANK_CODE
AND     ARRIVAL.ARRIVAL_TYPE = V_ARRIVAL_TYPE.TYPE_CODE
AND     PATIENT.RANK <> 20
AND     TO_CHAR(ARRIVAL.ARRIVAL_DATE,'DD-MM-YYYY') = '${DATE_IN}'
UNION
SELECT  50 RANK,V_RANKS.RAMK_NAME,ARRIVAL.ARRIVAL_TYPE,V_ARRIVAL_TYPE.TYPE_NAME,ARRIVAL.PATIENT_NUM
FROM ARRIVAL,PATIENT,V_RANKS,V_ARRIVAL_TYPE
WHERE ARRIVAL.PATIENT_NUM = PATIENT.PATIENT_NUM
AND     PATIENT.RANK = V_RANKS.RANK_CODE
AND     ARRIVAL.ARRIVAL_TYPE = V_ARRIVAL_TYPE.TYPE_CODE
AND     PATIENT.RANK = 20
AND     PATIENT.KINSHIP_PATIENT_NUM IS NULL
AND     TO_CHAR(ARRIVAL.ARRIVAL_DATE,'DD-MM-YYYY') = '${DATE_IN}'
UNION
SELECT 30 RANK,'عائلات ضباط' RAMK_NAME,ARRIVAL.ARRIVAL_TYPE,V_ARRIVAL_TYPE.TYPE_NAME,ARRIVAL.PATIENT_NUM
FROM ARRIVAL,PATIENT,V_RANKS,V_ARRIVAL_TYPE,PATIENT P2
WHERE ARRIVAL.PATIENT_NUM = PATIENT.PATIENT_NUM
AND     PATIENT.RANK = V_RANKS.RANK_CODE
AND     ARRIVAL.ARRIVAL_TYPE = V_ARRIVAL_TYPE.TYPE_CODE
AND     PATIENT.RANK = 20
AND     PATIENT.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM
AND     P2.RANK BETWEEN 1 AND 11
AND     TO_CHAR(ARRIVAL.ARRIVAL_DATE,'DD-MM-YYYY') = '${DATE_IN}'
UNION
SELECT 40 RANK,'عائلات صف' RAMK_NAME,ARRIVAL.ARRIVAL_TYPE,V_ARRIVAL_TYPE.TYPE_NAME,ARRIVAL.PATIENT_NUM
FROM ARRIVAL,PATIENT,V_RANKS,V_ARRIVAL_TYPE,PATIENT P2
WHERE ARRIVAL.PATIENT_NUM = PATIENT.PATIENT_NUM
AND     PATIENT.RANK = V_RANKS.RANK_CODE
AND     ARRIVAL.ARRIVAL_TYPE = V_ARRIVAL_TYPE.TYPE_CODE
AND     PATIENT.RANK = 20
AND     PATIENT.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM
AND     P2.RANK BETWEEN 12 AND 24
AND     TO_CHAR(ARRIVAL.ARRIVAL_DATE,'DD-MM-YYYY') = '${DATE_IN}'
    `;
    const result = await runQuery(query);
    res.status(200).json({ success: true, data: result });
  } catch (err) {
    console.error("Error in API endpoint:", err);
    res.status(500).json({ success: false, error: "Internal Server Error" });
  } finally {
    if (connection) {
      await closeDatabaseConnection(connection);
    }
  }
}
