import formatOracleDate from "@/lib/utils";

const {
  connectToDatabase,
  closeDatabaseConnection,
  runQuery,
} = require("../../lib/db");

export default async function handler(req, res) {
  let connection;

  try {
    connection = await connectToDatabase();

    // Your database queries or operations go here
    const FD = formatOracleDate(req.query.fdate);
    const TD = formatOracleDate(req.query.tdate);
    const query = `
    SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ضباط' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.RANK IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 22) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 3
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE NOT IN (8,90) )
UNION
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ضباط  صف' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.RANK IN (12, 13, 14, 15, 16, 17, 18, 19, 23) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 3
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE NOT IN (8,90) )
UNION
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ÚÇÆáÇÊ ÖÈÇØ' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT,PATIENT P2
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PATIENT.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM(+)
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.KINSHIP_PATIENT_NUM IS NOT NULL 
AND      P2.RANK IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 22) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 3
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE NOT IN (8,90) )
UNION
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ÚÇÆáÇÊ ÖÈÇØ ÕÝ' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT,PATIENT P2
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PATIENT.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM(+)
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.KINSHIP_PATIENT_NUM IS NOT NULL 
AND      P2.RANK IN (12, 13, 14, 15, 16, 17, 18, 19, 23) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 3
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE NOT IN (8,90) )
UNION
-------------------------------
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ÖÈÇØ' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.RANK IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 22) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 8
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE IN (8,90) )
UNION
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ÖÈÇØ ÕÝ' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.RANK IN (12, 13, 14, 15, 16, 17, 18, 19, 23) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 8
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE IN (8,90) )
UNION
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'عائلات ضباط' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT,PATIENT P2
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PATIENT.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM(+)
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.KINSHIP_PATIENT_NUM IS NOT NULL 
AND      P2.RANK IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 22) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 8
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE IN (8,90) )
UNION
SELECT DISTINCT PATIENT.PATIENT_NUM,PRESCRIPTION.PRESCRIPTION_TYPE,'ÚÇÆáÇÊ ÖÈÇØ ÕÝ' PATIENT_TYPE
FROM   PRESCRIPTION,PATIENT,PATIENT P2
WHERE PRESCRIPTION.PATIENT_NUM = PATIENT.PATIENT_NUM
AND      PATIENT.KINSHIP_PATIENT_NUM = P2.PATIENT_NUM(+)
AND      PRESCRIPTION.PRESCRIPTION_DATE >= '${FD}'
AND      PRESCRIPTION.PRESCRIPTION_DATE <= '${TD}'
AND      PATIENT.KINSHIP_PATIENT_NUM IS NOT NULL 
AND      P2.RANK IN (12, 13, 14, 15, 16, 17, 18, 19, 23) 
AND      PRESCRIPTION.PRESCRIPTION_TYPE = 8
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE
                        WHERE    PRESCRIPTION_MEDICINE.PRESCRIPTION_SERIAL = PRESCRIPTION.PRESCRIPTION_SERIAL
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_DATE = PRESCRIPTION.PRESCRIPTION_DATE
                        AND        PRESCRIPTION_MEDICINE.PRESCRIPTION_TYPE = PRESCRIPTION.PRESCRIPTION_TYPE)
AND     EXISTS (SELECT 1 
                        FROM    PRESCRIPTION_MEDICINE_MON,CLINIC1
                        WHERE   PRESCRIPTION_MEDICINE_MON.PATIENT_NUM = PRESCRIPTION.PATIENT_NUM
                        AND       PRESCRIPTION_MEDICINE_MON.CLINIC_CODE = CLINIC1.CLINIC_CODE
                        AND      CLINIC1.SPECIALISIM_CODE IN (8,90) )
    `;
    const result = await runQuery(query);
    res.status(200).json({ success: true, data: result });
  } catch (err) {
    console.error("Error in API endpoint:", err);
    res.status(500).json({ success: false, error: "Internal Server Error" });
  } finally {
    if (connection) {
      await closeDatabaseConnection(connection);
    }
  }
}
